devbus/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField,
                     TextAreaField, RadioField)
from wtforms.validators import DataRequired, Length


class NewPostForm(FlaskForm):
    post_title = StringField('Post Title',
                             validators=[DataRequired(), Length(max=86)])
    post_content = TextAreaField('Post Content',
                                 validators=[DataRequired(), Length(max=350)])
    code_content = TextAreaField('Code Content',
                                 validators=[])
    code_language = StringField('Code Language')
    post_type = (RadioField("Post Type",
                 choices=["post", "assist"], default="post"))
    submit = SubmitField('POST')


class NewCommentForm(FlaskForm):
    comment_content = TextAreaField()
    code_language = StringField()
    code_content = TextAreaField()
    submit = SubmitField('POST')


class NewSubCommentForm(FlaskForm):
    comment_content = TextAreaField()
    code_language = StringField()
    code_content = TextAreaField()
    submit = SubmitField('POST')

devbus/main/routes.py
from flask import render_template, Blueprint, redirect, flash, jsonify, request
from flask_login import login_required
from devbus.utils.models import Post, User, DoesNotExist

main = Blueprint("main", "__name__")


@main.route("/")
def home():
    """
    This function renders the home page and provides
    a list of all posts in chronological order.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    posts = Post.objects().order_by('-created_date').paginate(
        page=page_num,
        per_page=10)
    return render_template("main/home.html",
                           posts=posts,
                           page_num=page_num)


@main.route("/user/<username>")
@login_required
def view_user(username):
    try:
        try:
            page_num = int(request.args.get('page'))
        except TypeError:
            page_num = 1
        user = User.objects.get(username=username)
        posts = (Post.objects(created_by=user.id)
                 .paginate(page=page_num, per_page=10)
                 if user is not None else None)
        return render_template("main/view_user.html",
                               title=username, user=user, posts=posts)
    except DoesNotExist:
        flash('''User you are looking for does not exist or
         has been deactivated''', "red")
    return redirect("/")


@main.route("/search", methods=["GET", "POST"])
@main.route("/search/<filter>", methods=["GET", "POST"])
@main.route("/search/<filter>/<arg>", methods=["GET", "POST"])
@login_required
def search_results(arg="", filter=""):
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    if (arg == ""):
        arg = request.form.get('search_field')
        filter = request.form.get('filter_select')
    match filter:
        case "user":
            users = User.objects(username__icontains=arg)
            posts = (Post.objects(created_by__in=users)
                     .paginate(page=page_num, per_page=10))
        case "lang":
            users = User.objects(languages__icontains=arg)
            posts = (Post.objects(code_language__icontains=arg)
                     .paginate(page=page_num, per_page=10))
        case _:
            users = (User.objects() if arg == ""
                     else User.objects(username__icontains=arg))
            posts = Post.objects().paginate(page=page_num, per_page=10)
    return render_template("main/search_results.html",
                           title="Search Results", posts=posts,
                           users=users, page_num=page_num)


@main.route("/_search/<filter>/<arg>", methods=["GET", "POST"])
@login_required
def search(arg=None, filter="user"):
    match filter:
        case "user":
            items = User.objects(username__icontains=arg)
        case "lang":
            items = Post.objects(code_language__icontains=arg)
        case _:
            return jsonify(False)
    return jsonify(items=items)

devbus/posts/routes.py
from flask import (Blueprint, render_template, redirect,
                   request, jsonify, flash, abort)
from flask_login import login_required, current_user
from devbus.utils.models import Post, Comment, Subcomment
from devbus.posts.forms import NewPostForm, NewCommentForm, NewSubCommentForm


posts = Blueprint("posts", "__name__")


@posts.route("/posts/<id>", methods=["GET", "POST"])
@login_required
def view_post(id):
    """
    Returns the post on which the user has clicked
    into single view, loading all comments.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get_or_404(id=id)
    comments = Post.objects.paginate_field('comments',
                                           page=page_num,
                                           per_page=10,
                                           doc_id=id)
    return render_template("posts/view_post.html", title="View Post",
                           post=post, comments=comments, page_num=page_num)


@posts.route("/posts/<id>/edit_post", methods=["GET", "POST"])
@login_required
def edit_post(id):
    """
    Allows the user to edit their own posts, once
    saved redirects back to view_post view.
    """
    post = Post.objects.get(id=id)
    if post.created_by != current_user:
        abort(403)
    form = NewPostForm()
    if form.validate_on_submit():
        form.populate_obj(post)
        post.created_by = current_user.id
        post.save()
        flash("Your post has been edited!", 'message')
        return redirect(f"/posts/{post.id}")
    elif request.method == "GET":
        form.post_title.data = post.post_title
        form.post_content.data = post.post_content
        form.code_language.data = post.code_language
        form.code_content.data = post.code_content
        form.post_type.data = post.post_type
    return render_template("posts/edit_post.html", title="Edit Post",
                           form=form, post=post)


@posts.route("/posts/<post_id>/<comment_id>", methods=["GET", "POST"])
@login_required
def view_comment(post_id, comment_id):
    """
    Returns the comment, and the post it belongs to,
    on which the user has clicked into single view,
    loading all subcomments.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    subcomments = Comment.objects.paginate_field('comments',
                                                 page=page_num,
                                                 per_page=10,
                                                 doc_id=comment_id)
    return render_template("posts/view_comment.html", title="View Comment",
                           post=post, comment=comment,
                           subcomments=subcomments,
                           page_num=page_num)


@posts.route("/posts/<id>/reply", methods=["GET", "POST"])
@login_required
def new_comment(id):
    """
    Renders same template as view_post, but with
    an additional form variable, created with WTForms.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get(id=id)
    form = NewCommentForm()
    comments = Post.objects.paginate_field('comments',
                                           page=page_num,
                                           per_page=10,
                                           doc_id=id)
    if form.validate_on_submit():
        comment = Comment(created_by=current_user.id)
        form.populate_obj(comment)
        comment.save()
        post.comments.append(comment)
        post.save()
        flash("Your comment has been posted!", 'message')
        return redirect(f"/posts/{id}")
    return render_template("posts/view_post.html", title="New Comment",
                           post=post,
                           form=form,
                           comments=comments,
                           page_num=page_num)


@posts.route("/posts/<post_id>/<comment_id>/edit_reply", methods=["GET",
                                                                  "POST"])
@login_required
def edit_comment(post_id, comment_id):
    """
    Allows the user to edit their own comment, once
    saved redirects back to the post.
    """
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    if comment.created_by != current_user:
        abort(403)
    form = NewCommentForm()
    if form.validate_on_submit():
        form.populate_obj(comment)
        comment.save()
        flash("Your comment has been edited!", 'message')
        return redirect(f"/posts/{post_id}")
    elif request.method == "GET":
        form.comment_content.data = comment.comment_content
        form.code_language.data = comment.code_language
        form.code_content.data = comment.code_content
    return render_template("posts/edit_comment.html", title="Edit Comment",
                           post=post,
                           comment=comment,
                           form=form)


@posts.route("/posts/<post_id>/<comment_id>/reply", methods=["GET", "POST"])
@login_required
def new_subcomment(post_id, comment_id):
    """
    Similar to view comment, but instead passes an additional
    form variable, containing a form created with WTForms.
    On submit redirects to post page.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    subcomments = Comment.objects.paginate_field('comments',
                                                 page=page_num,
                                                 per_page=10,
                                                 doc_id=comment_id)
    sub_form = NewSubCommentForm()
    if sub_form.validate_on_submit():
        sub_comment = Subcomment(created_by=current_user.id)
        sub_form.populate_obj(sub_comment)
        comment.comments.append(sub_comment)
        sub_comment.save()
        comment.save()
        flash("Your comment has been posted!", 'message')
        return redirect(f"/posts/{post_id}/{comment_id}")
    return render_template("posts/view_comment.html", title="New Subcomment",
                           post=post,
                           comment=comment,
                           sub_form=sub_form,
                           subcomments=subcomments,
                           page_num=page_num)


@posts.route("/posts/<post_id>/<comment_id>/<subcomment_id>/edit_subreply",
             methods=["GET", "POST"])
@login_required
def edit_subcomment(post_id, comment_id, subcomment_id):
    """
    Renders a WTForm, similar to add_subcomment, which
    allows the user to edit their subcomment. On successful
    submission, redirects back to view comment page.
    """
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    subcomment = Comment.objects.get(id=subcomment_id)
    if subcomment.created_by != current_user:
        abort(403)
    form = NewSubCommentForm()
    if form.validate_on_submit():
        form.populate_obj(subcomment)
        subcomment.save()
        flash("Your comment has been edited!", 'message')
        return redirect(f"/posts/{post_id}/{comment_id}")
    elif request.method == "GET":
        form.comment_content.data = subcomment.comment_content
    return render_template(
        "posts/edit_subcomment.html",
        title="Edit Subcomment",
        post=post,
        comment=comment,
        subcomment=subcomment,
        form=form,
    )


@posts.route("/new_post", methods=["GET", "POST"])
@login_required
def new_post():
    """
    Providers a form, created with WTForms, which allows the
    user to create a new post.
    """
    form = NewPostForm()
    if form.validate_on_submit():
        post = Post()
        form.populate_obj(post)
        post.created_by = current_user.id
        post.save()
        flash("Your post has been created!", 'message')
        return redirect(f"/posts/{post.id}")
    return render_template("posts/new_post.html", title="New Post", form=form)


@posts.route("/_update_votes/<id>/<vote>", methods=["GET", "POST"])
def update_votes(id, vote):
    """
    Function does not render/use a template at all; this is the back-end
    logic of the post and comments vote buttons. Depending on the button
    pressed updates the database and then sends a JSON response to the AJAX
    in the front end to update visually.
    """
    if current_user.is_authenticated is False:
        flash("You must be signed in to do that!", "red")
        return jsonify(False)
    post_set = Post.objects(id=id).first()
    comment_set = Comment.objects(id=id).first()
    content = post_set if post_set is not None else comment_set
    if current_user in content.votes["up"] and vote == "up":
        # If the user has upvoted before, and is pressing upvote btn again
        content.votes["up"].remove(current_user)
    elif current_user in content.votes["up"] and vote == "down":
        # If the user has upvoted before, and is pressing downvote btn
        content.votes["up"].remove(current_user)
        content.votes["down"].append(current_user)
    elif current_user in content.votes["down"] and vote == "up":
        # If the user has downvoted before, and is pressing upvote btn
        content.votes["down"].remove(current_user)
        content.votes["up"].append(current_user)
    elif current_user in content.votes["down"] and vote == "down":
        # If the user has downvoted before, and is pressing downvote btn again
        content.votes["down"].remove(current_user)
    else:
        # If the user has never voted before
        content.votes[vote].append(current_user)
    content.save()
    return jsonify(

devbus/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block content %}
<!-- Edit Post Form -->
<div class="row">
    <form id="edit_post" class="col s12 m8 offset-m2 l6 offset-l3 grey lighten-3 center-align new" method="POST">
        <fieldset class="row">
            <legend class="deep-purple-text text-darken-3">Edit Post</legend>
            <a href="#delete_post" class="waves-effect waves-light btn-small red darken-2 white-text right modal-trigger"><i class="fa-solid fa-trash-can"></i><span class="visually-hidden">Delete Post</span></a>
            {{ form.hidden_tag() }}
            {% for subfield in form.post_type %}
            <div class="col s6 m3">
                <p>
                    <label>
                        {% if post.post_type == "assist" and subfield.id == "post_type-1" %}
                        {{ subfield(checked=True)  }}
                        {% else %}
                        {{ subfield  }}
                        {% endif %}
                        <span>{{ subfield.object_data | capitalize }}</span>
                    </label>
                </p>
            </div>
            {% endfor %}
            <div class="col s12 m6 center">
                <span>Code Area</span>
                <div class="switch">
                    <label>
                        O
                        <input type="checkbox" id="code_switch" name="code_switch" {% if post.code_content %} checked {% endif%}>
                        <span class="lever"></span>
                        I
                    </label>
                </div>
            </div>
            <div class="input-field col s12">
                {% if form.post_title.errors %}
                {{ form.post_title(class="invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.post_title.errors %}
                    <span class="red-text">{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.post_title }}
                {% endif %}
                {{ form.post_title.label }}
            </div>
            <div class="input-field col s12">
                {% if form.post_content.errors %}
                {{ form.post_content(class="materialize-textarea invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.post_content.errors %}
                    <span class="red-text">{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.post_content(class="materialize-textarea") }}
                {% endif %}
                {{ form.post_content.label }}
            </div>
            <div class="input-field col s6 {% if not post.code_content %} visually-hidden {% endif%} code-switch">
                {{ form.code_language(class="autocomplete") }}
                {{ form.code_language.label }}
            </div>
            <div class="input-field col s12 {% if not post.code_content %} visually-hidden {% endif%} code-switch">
                {% if form.code_content.errors %}
                {{ form.code_content(class="materialize-textarea grey darken-4 white-text invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.code_content.errors %}
                    <span class="red-text">{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.code_content(class="materialize-textarea grey darken-4 white-text") }}
                {% endif %}
                {{ form.code_content.label(class="visually-hidden") }}
            </div>
            <div class="input-field col s12">
                {{ form.submit(class="waves-effect waves-light btn yellow") }}
                <a href="{{ url_for('posts.view_post', id=post.id)}}" class="waves-effect waves-light btn red darken-2 white-text">Cancel</a>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

{% block modals %}
<div id="delete_post" class="modal">
    <div class="modal-content">
        <h4>Confirm Deletion</h4>
        <p>Are you sure you want to delete this post?</p>
    </div>
    <div class="modal-footer center">
        <a href="{{ url_for('posts.delete_post', id=post.id)}}" class="waves-effect waves-green btn-flat">Yes</a>
        <a class="modal-close waves-effect waves-green btn-flat">No</a>
    </div>
</div>
{% endblock %}

devbus/templates/posts/view_comment.html
{% extends 'base.html' %}

{% block content %}

{% include 'sidenavs.html' %}
<!-- Post -->
<div class="row">
    {% if current_user.is_authenticated %}
    <div class="col s12 m9 offset-m4 l8 push-l2">
        {% else %}
        <div class="col s12 m10 push-m1 l8 push-l2">
            {% endif %}
        <div class="post card grey lighten-1">
            <div class="card-panel z-depth-1 valign-wrapper">
                <div class="col s3 m2">
                    <img src="{{ post.created_by.profile_image }}" alt="User's profile picture"
                        class="circle responsive-img">
                </div>
                <div class="col s10">
                    <a href="{{ url_for('main.view_user', username=post.created_by.username) }}">{{ post.created_by.username }}</a>
                    <span class="grey-text text-darken-2">{{ post.created_date.strftime('%Y-%m-%d') }}</span>
                    <div class="card-title-container">
                        <span class="card-title flow-text">{{ post.post_title }}</span>
                    </div>
                </div>
            </div>
            <p class="card-content">{{ post.post_content }}</p>
            {% if post.code_content %}
            <div class="card-content code-content">
                <div class="chip deep-purple-text text-darken-3 z-depth-1">{{ post.code_language }}</div>
                <pre
                    class="z-depth-2"><code class="language-{{ post.code_language }}">{{ post.code_content }}</code></pre>
            </div>
            {% endif %}
            <div class="card-action grey lighten-2 z-depth-1">
                {% if post.post_type == "post" %}
                <a href="{{ url_for('posts.update_votes', id=post.id, vote='up') }}"
                    class="waves-effect waves-dark btn-flat vote-button">
                    <i
                        class="material-icons right green-text {% if current_user in post.votes.up %} text-darken-3 {% else %} text-lighten-2 {% endif %}">
                        thumb_up
                    </i>
                    <span>
                        {{ post.votes.up|length }}
                    </span>
                </a>
                <a href="{{ url_for('posts.update_votes', id=post.id, vote='down') }}"
                    class="waves-effect btn-flat vote-button">
                    <i
                        class="material-icons right small red-text {% if current_user in post.votes.down %} text-darken-3 {% else %} text-lighten-2 {% endif %}">
                        thumb_down
                    </i>
                    <span>
                        {{ post.votes.down|length }}
                    </span>
                </a>
                <a href="{{ url_for('posts.new_comment', id=post.id)}}"
                    class="waves-effect waves-light btn right">Reply</a>
                {% if current_user == post.created_by %}
                <a href="{{ url_for('posts.edit_post', id=post.id)}}"
                    class="waves-effect waves-light red darken-2 btn white-text tooltipped right"
                    data-position="left" data-tooltip="Edit Post"><i class="fa-solid fa-file-pen"></i><span class="visually-hidden">Edit Post</span></a>
                {% endif %}
                <a href="{{ url_for('posts.view_post', id=post.id)}}"
                    class="waves-effect btn-flat grey-text text-darken-2 right"><i
                        class="material-icons right small">chat</i><span>{{ post.comments|length }}
                        {% if post.comments|length == 1 %} comment {% else %} comments {% endif %}</span>
                </a>
                {% else %}
                <a href="{{ url_for('posts.new_comment', id=post.id)}}"
                    class="waves-effect waves-light deep-purple darken-3 btn white-text">Assist</a>
                {% if current_user == post.created_by %}
                <a href="{{ url_for('posts.edit_post', id=post.id)}}"
                    class="waves-effect waves-light materialize-red white-text lighten-1 btn tooltipped"
                    data-position="right" data-tooltip="Edit Post"><i class="fa-solid fa-file-pen"></i><span class="visually-hidden">Edit Post</span></a>
                {% endif %}
                <a href="{{ url_for('posts.view_post', id=post.id)}}"
                    class="waves-effect btn-flat grey-text text-darken-2 right">
                    <i class="material-icons small right">chat</i>
                    <span>{{ post.comments|length }} {% if post.comments|length == 1 %} assist {% else %} assists
                        {% endif %}</span>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="divider"></div>
<!-- Comment -->
<div class="row">
    {% if current_user.is_authenticated %}
    <div class="comment col s12 m9 offset-m4 l8 push-l2">
        {% else %}
        <div class="comment col s12 m10 push-m1 l8 push-l2">
            {% endif %}
        <div class="card col grey lighten-2">
            <div class="col hide-on-small-only m2 comment-user-info center-align">
                <img src="{{ comment.created_by.profile_image }}" alt="User's profile picture"
                    class="circle responsive-img">
            </div>
            <div class="col s12 m8 card-content">
                <a href="{{ url_for('main.view_user', username=comment.created_by.username) }}">{{ comment.created_by.username }}</a>
                <span class="grey-text text-darken-2">{{ comment.created_date.strftime('%Y-%m-%d') }}</span>
                {% if current_user == comment.created_by %}
                <a href="{{ url_for('posts.edit_comment', post_id=post.id, comment_id=comment.id)}}" class="crud-btn btn-flat blue-text text-darken-4">EDIT</a>
                <a href="#delete_comment" data-uid="{{comment.id}}" class="crud-btn btn-flat red-text text-darken-2 modal-trigger">DELETE</a>
                {% endif %}
            </div>
            <div class="col s12 m8 card-content">
                <p>{{ comment.comment_content }}</p>
            </div>
            {% if comment.code_language and comment.code_content %}
            <div class="col s12 m10 card-content">
                <div class="chip deep-purple-text text-darken-3 z-depth-1">{{ comment.code_language }}</div>
                <pre
                    class="z-depth-2"><code class="language-{{ comment.code_language }}">{{ comment.code_content }}</code></pre>
            </div>
            {% endif %}
            <div class="col s12 card-action">
                <a href="{{ url_for('posts.update_votes', id=comment.id, vote='up') }}"
                    class="waves-effect waves-dark btn-flat vote-button">
                    <i
                        class="material-icons right green-text {% if current_user in comment.votes.up %} accent-4 {% else %} text-lighten-2 {% endif %}">
                        thumb_up
                    </i>
                    <span>
                        {{ comment.votes.up|length }}
                    </span>
                </a>
                <a href="{{ url_for('posts.update_votes', id=comment.id, vote='down') }}"
                    class="waves-effect btn-flat vote-button">
                    <i
                        class="material-icons right small red-text {% if current_user in comment.votes.down %} accent-4 {% else %} text-lighten-2 {% endif %}">
                        thumb_down
                    </i>
                    <span>
                        {{ comment.votes.down|length }}
                    </span>
                </a>
                <a href="{{ url_for('posts.new_subcomment', post_id=post.id, comment_id=comment.id, page=page_num)}}"
                    class="waves-effect waves-light btn-flat right">Reply</a>
                <div class="waves-effect btn-flat right">
                    <i class="material-icons right small grey-text text-darken-2">chat</i>
                    <span>{{ comment.comments|length }}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- Subcomments -->
    {% for subcomment in subcomments.items %}
    <div class="subcomment col s11 offset-s1 m9 offset-m2 l7 offset-l3">
        <div class="card col s12 grey lighten-2">
            <div class="col hide-on-small-only m2 comment-user-info center-align">
                <img src="{{ subcomment.created_by.profile_image }}" alt="User's profile picture"
                    class="circle responsive-img">
            </div>
            <div class="col s12 m10 card-content">
                <a href="{{ url_for('main.view_user', username=post.created_by.username) }}">{{ subcomment.created_by.username }}</a>
                <span class="grey-text text-darken-2">{{ subcomment.created_date.strftime('%Y-%m-%d') }}</span>
                {% if current_user == subcomment.created_by %}
                <a href="{{ url_for('posts.edit_subcomment', post_id=post.id, comment_id=comment.id, subcomment_id=subcomment.id) }}" class="crud-btn btn-flat blue-text text-darken-4">EDIT</a>
                <a href="#delete_comment" data-uid="{{comment.id}}" data-suid="{{subcomment.id}}" class="crud-btn btn-flat red-text text-darken-2 modal-trigger">DELETE</a>
                {% endif %}
            </div>
            <div class="col s12 m10 card-content">
                <p>{{ subcomment.comment_content }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- Pagination -->
    {% macro render_navigation(pagination, endpoint) %}
    {% if pagination.pages > 1 %}
    <div class="row">
        <div class="col s12 m9 offset-m4 l8 push-l2 center">
            <ul class=pagination>
                {% if pagination.has_prev %}
                <li class="waves-effect"><a href="{{ url_for(endpoint, page=page_num-1) }}"><i
                            class="material-icons yellow-text">chevron_left</i></a></li>
                {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                {% endif %}
                {% for page in pagination.iter_pages() %}
                {% if page %}
                {% if page != pagination.page %}
                <li class="waves-effect"><a class="yellow-text" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                </li>
                {% else %}
                <li class="active"><a href="#!">{{ page }}</a></li>
                {% endif %}
                {% endif %}
                {% endfor %}
                {% if pagination.has_next %}
                <li class="waves-effect"><a href="{{ url_for(endpoint, page=page_num+1) }}"><i
                            class="material-icons yellow-text">chevron_right</i></a></li>
                {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% endif %}
    {% endmacro %}

    {{ render_navigation(subcomments, 'posts.view_comment') }}
</div>
{% if sub_form %}
<div class="divider"></div>
<div class="row">
    {% if current_user.is_authenticated %}
    <form id="new_subcomment" class="col s11 offset-s1 m8 offset-m5 l7 offset-l3 center-align new" method="POST">
        {% else %}
        <form id="new_subcomment" class="col s11 offset-s1 m9 offset-m2 l7 offset-l3 center-align new" method="POST">
            {% endif %}
        <fieldset class="card valign-wrapper">
            <legend class="visually-hidden">SubComment</legend>
            {{ sub_form.hidden_tag() }}
            <div class="col s4 m3 xl2 grey lighten-1 card-panel comment-user-info">
                <img src="{{ current_user.profile_image }}" alt="User's profile picture" class="circle responsive-img">
            </div>
            <div class="col s8 m9 xl10">
                <div class="input-field col s12">
                    {% if sub_form.comment_content.errors %}
                    {{ sub_form.comment_content(class="materialize-textarea invalid") }}
                    <div class="invalid-feedback">
                        {% for error in sub_form.comment_content.errors %}
                        <span class="red-text">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ sub_form.comment_content(class="materialize-textarea") }}
                    {% endif %}
                    {{ sub_form.comment_content.label }}
                </div>
                {{ sub_form.submit(class="waves-effect waves-light btn-small yellow") }}
            </div>
        </fieldset>
    </form>
</div>
{% endif %}
{% endblock %}

{% block modals %}
<div id="delete_comment" class="modal">
    <div class="modal-content">
        <h4>Confirm Deletion</h4>
        <p>Are you sure you want to delete your comment?</p>
    </div>
    <div class="modal-footer center">
        <a href="#!" class="waves-effect waves-green btn-flat">Yes</a>
        <a class="modal-close waves-effect waves-green btn-flat">No</a>
    </div>
</div>
{% endblock %}