devbus/main/routes.py
from flask import render_template, Blueprint, redirect, flash, jsonify, request
from flask_login import login_required
from devbus.utils.models import Post, User, DoesNotExist

main = Blueprint("main", "__name__")


@main.route("/")
def home():
    """
    This function renders the home page and provides
    a list of all posts in chronological order.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    posts = Post.objects().order_by('-created_date').paginate(
        page=page_num,
        per_page=10)
    return render_template("main/home.html",
                           posts=posts,
                           page_num=page_num)


@main.route("/user/<username>")
@login_required
def view_user(username):
    try:
        try:
            page_num = int(request.args.get('page'))
        except TypeError:
            page_num = 1
        user = User.objects.get(username=username)
        posts = (Post.objects(created_by=user.id)
                 .paginate(page=page_num, per_page=10)
                 if user is not None else None)
        return render_template("main/view_user.html",
                               title=username, user=user, posts=posts)
    except DoesNotExist:
        flash('''User you are looking for does not exist or
         has been deactivated''', "red")
    return redirect("/")


@main.route("/search", methods=["GET", "POST"])
@main.route("/search/<filter>", methods=["GET", "POST"])
@main.route("/search/<filter>/<arg>", methods=["GET", "POST"])
@login_required
def search_results(arg="", filter=""):
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    if (arg == ""):
        arg = request.form.get('search_field')
        filter = request.form.get('filter_select')
    match filter:
        case "user":
            users = User.objects(username__icontains=arg)
            posts = (Post.objects(created_by__in=users)
                     .paginate(page=page_num, per_page=10))
        case "lang":
            users = User.objects(languages__icontains=arg)
            posts = (Post.objects(code_language__icontains=arg)
                     .paginate(page=page_num, per_page=10))
        case _:
            users = (User.objects() if arg == ""
                     else User.objects(username__icontains=arg))
            posts = Post.objects().paginate(page=page_num, per_page=10)
    return render_template("main/search_results.html",
                           title="Search Results", posts=posts,
                           users=users, page_num=page_num)


@main.route("/_search/<filter>/<arg>", methods=["GET", "POST"])
@login_required
def search(arg=None, filter="user"):
    match filter:
        case "user":
            items = User.objects(username__icontains=arg)
        case "lang":
            items = Post.objects(code_language__icontains=arg)
        case _:
            return jsonify(False)
    return jsonify(items=items)

devbus/posts/routes.py
from flask import (Blueprint, render_template, redirect,
                   request, jsonify, flash, abort)
from flask_login import login_required, current_user
from devbus.utils.models import Post, Comment, Subcomment
from devbus.posts.forms import NewPostForm, NewCommentForm, NewSubCommentForm


posts = Blueprint("posts", "__name__")


@posts.route("/posts/<id>", methods=["GET", "POST"])
@login_required
def view_post(id):
    """
    Returns the post on which the user has clicked
    into single view, loading all comments.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get_or_404(id=id)
    comments = Post.objects.paginate_field('comments',
                                           page=page_num,
                                           per_page=10,
                                           doc_id=id)
    return render_template("posts/view_post.html", title="View Post",
                           post=post, comments=comments, page_num=page_num)


@posts.route("/posts/<id>/edit_post", methods=["GET", "POST"])
@login_required
def edit_post(id):
    """
    Allows the user to edit their own posts, once
    saved redirects back to view_post view.
    """
    post = Post.objects.get(id=id)
    if post.created_by != current_user:
        abort(403)
    form = NewPostForm()
    if form.validate_on_submit():
        form.populate_obj(post)
        post.created_by = current_user.id
        post.save()
        flash("Your post has been edited!", 'message')
        return redirect(f"/posts/{post.id}")
    elif request.method == "GET":
        form.post_title.data = post.post_title
        form.post_content.data = post.post_content
        form.code_language.data = post.code_language
        form.code_content.data = post.code_content
        form.post_type.data = post.post_type
    return render_template("posts/edit_post.html", title="Edit Post",
                           form=form, post=post)


@posts.route("/posts/<post_id>/<comment_id>", methods=["GET", "POST"])
@login_required
def view_comment(post_id, comment_id):
    """
    Returns the comment, and the post it belongs to,
    on which the user has clicked into single view,
    loading all subcomments.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    subcomments = Comment.objects.paginate_field('comments',
                                                 page=page_num,
                                                 per_page=10,
                                                 doc_id=comment_id)
    return render_template("posts/view_comment.html", title="View Comment",
                           post=post, comment=comment,
                           subcomments=subcomments,
                           page_num=page_num)


@posts.route("/posts/<id>/reply", methods=["GET", "POST"])
@login_required
def new_comment(id):
    """
    Renders same template as view_post, but with
    an additional form variable, created with WTForms.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get(id=id)
    form = NewCommentForm()
    comments = Post.objects.paginate_field('comments',
                                           page=page_num,
                                           per_page=10,
                                           doc_id=id)
    if form.validate_on_submit():
        comment = Comment(created_by=current_user.id)
        form.populate_obj(comment)
        comment.save()
        post.comments.append(comment)
        post.save()
        flash("Your comment has been posted!", 'message')
        return redirect(f"/posts/{id}")
    return render_template("posts/view_post.html", title="New Comment",
                           post=post,
                           form=form,
                           comments=comments,
                           page_num=page_num)


@posts.route("/posts/<post_id>/<comment_id>/edit_reply", methods=["GET",
                                                                  "POST"])
@login_required
def edit_comment(post_id, comment_id):
    """
    Allows the user to edit their own comment, once
    saved redirects back to the post.
    """
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    if comment.created_by != current_user:
        abort(403)
    form = NewCommentForm()
    if form.validate_on_submit():
        form.populate_obj(comment)
        comment.save()
        flash("Your comment has been edited!", 'message')
        return redirect(f"/posts/{post_id}")
    elif request.method == "GET":
        form.comment_content.data = comment.comment_content
        form.code_language.data = comment.code_language
        form.code_content.data = comment.code_content
    return render_template("posts/edit_comment.html", title="Edit Comment",
                           post=post,
                           comment=comment,
                           form=form)


@posts.route("/posts/<post_id>/<comment_id>/reply", methods=["GET", "POST"])
@login_required
def new_subcomment(post_id, comment_id):
    """
    Similar to view comment, but instead passes an additional
    form variable, containing a form created with WTForms.
    On submit redirects to post page.
    """
    try:
        page_num = int(request.args.get('page'))
    except TypeError:
        page_num = 1
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    subcomments = Comment.objects.paginate_field('comments',
                                                 page=page_num,
                                                 per_page=10,
                                                 doc_id=comment_id)
    sub_form = NewSubCommentForm()
    if sub_form.validate_on_submit():
        sub_comment = Subcomment(created_by=current_user.id)
        sub_form.populate_obj(sub_comment)
        comment.comments.append(sub_comment)
        sub_comment.save()
        comment.save()
        flash("Your comment has been posted!", 'message')
        return redirect(f"/posts/{post_id}/{comment_id}")
    return render_template("posts/view_comment.html", title="New Subcomment",
                           post=post,
                           comment=comment,
                           sub_form=sub_form,
                           subcomments=subcomments,
                           page_num=page_num)


@posts.route("/posts/<post_id>/<comment_id>/<subcomment_id>/edit_subreply",
             methods=["GET", "POST"])
@login_required
def edit_subcomment(post_id, comment_id, subcomment_id):
    """
    Renders a WTForm, similar to add_subcomment, which
    allows the user to edit their subcomment. On successful
    submission, redirects back to view comment page.
    """
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    subcomment = Comment.objects.get(id=subcomment_id)
    if subcomment.created_by != current_user:
        abort(403)
    form = NewSubCommentForm()
    if form.validate_on_submit():
        form.populate_obj(subcomment)
        subcomment.save()
        flash("Your comment has been edited!", 'message')
        return redirect(f"/posts/{post_id}/{comment_id}")
    elif request.method == "GET":
        form.comment_content.data = subcomment.comment_content
    return render_template(
        "posts/edit_subcomment.html",
        title="Edit Subcomment",
        post=post,
        comment=comment,
        subcomment=subcomment,
        form=form,
    )


@posts.route("/new_post", methods=["GET", "POST"])
@login_required
def new_post():
    """
    Providers a form, created with WTForms, which allows the
    user to create a new post.
    """
    form = NewPostForm()
    if form.validate_on_submit():
        post = Post()
        form.populate_obj(post)
        post.created_by = current_user.id
        post.save()
        flash("Your post has been created!", 'message')
        return redirect(f"/posts/{post.id}")
    return render_template("posts/new_post.html", title="New Post", form=form)


@posts.route("/_update_votes/<id>/<vote>", methods=["GET", "POST"])
def update_votes(id, vote):
    """
    Function does not render/use a template at all; this is the back-end
    logic of the post and comments vote buttons. Depending on the button
    pressed updates the database and then sends a JSON response to the AJAX
    in the front end to update visually.
    """
    if current_user.is_authenticated is False:
        flash("You must be signed in to do that!", "red")
        return jsonify(False)
    post_set = Post.objects(id=id).first()
    comment_set = Comment.objects(id=id).first()
    content = post_set if post_set is not None else comment_set
    if current_user in content.votes["up"] and vote == "up":
        # If the user has upvoted before, and is pressing upvote btn again
        content.votes["up"].remove(current_user)
    elif current_user in content.votes["up"] and vote == "down":
        # If the user has upvoted before, and is pressing downvote btn
        content.votes["up"].remove(current_user)
        content.votes["down"].append(current_user)
    elif current_user in content.votes["down"] and vote == "up":
        # If the user has downvoted before, and is pressing upvote btn
        content.votes["down"].remove(current_user)
        content.votes["up"].append(current_user)
    elif current_user in content.votes["down"] and vote == "down":
        # If the user has downvoted before, and is pressing downvote btn again
        content.votes["down"].remove(current_user)
    else:
        # If the user has never voted before
        content.votes[vote].append(current_user)
    content.save()
    return jsonify(

devbus/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="DevBus | Social Media for Developers">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/favicon_io/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon_io/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon_io/favicon-16x16.png')}}">
    <link rel="manifest" href="{{ url_for('static', filename='images/favicon_io/site.webmanifest')}}">
    <!-- Material Icons CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- PrismJS CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/prism.css')}}">
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/materialize.min.css')}}">
    <!-- Own CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
    {% if title %}
    <title>{{ title }} | DevBus</title>
    {% else %}
    <title>DevBus | If StackOverflow and Twitter had a child.</title>
    {% endif %}
    <!-- FontAwesome Script -->
    <script src="https://kit.fontawesome.com/f05b6615ad.js" crossorigin="anonymous"></script>
</head>

<body class="grey darken-3">
    <header>
        <nav>
            <!-- Navbar -->
            <div class="container nav-wrapper">
                <a href="{{ url_for('main.home')}}" class="brand-logo hide-on-small-only">DevBus</a>
                <a href="{{ url_for('main.home')}}" class="brand-logo hide-on-med-and-up">DB</a>
                <a data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                {% if current_user.is_authenticated %}
                <ul class="right">
                    <li><a data-target="search-field--container" class="autocomplete-trigger" data-position="left"><i
                                class="material-icons">search</i><span class="visually-hidden">Show/Hide
                                Search</span></a></li>
                    <li class="hide-on-med-and-down"><a href="{{ url_for('auth.profile')}}">My Profile</a></li>
                    {% if current_user.is_active and current_user.is_authenticated and current_user.user_type == 'superuser' %}
                    <li><a href="/admin"
                            class="waves-effect waves-light btn-small tooltipped blue darken-2 white-text hide-on-small-and-down"
                            data-position="bottom" data-tooltip="Admin Page"><i class="fa-solid fa-user-gear"></i><span
                                class="visually-hidden">Open Admin Page</span></a></li>
                    {% endif %}
                    <li><a href="#log_out"
                            class="hide-on-small-only waves-effect waves-light btn-small tooltipped modal-trigger"
                            data-position="bottom" data-tooltip="Sign Out"><i
                                class="fa-solid fa-right-to-bracket"></i><span class="visually-hidden">Log Out</span></a></li>
                    {% else %}
                    <ul class="right hide-on-med-and-down">
                        <li>
                            <a data-target="search-field--container" class="autocomplete-trigger">
                                <i class="material-icons">search</i>
                                <span class="visually-hidden">Show Search Field</span>
                            </a>
                        </li>
                        <li><a href="{{ url_for('main.home')}}">Home</a></li>
                        <li><a href="{{ url_for('auth.signin')}}">Sign In</a></li>
                        <li><a href="{{ url_for('auth.signup')}}" class="waves-effect waves-light btn">Sign Up</a></li>
                        {% endif %}
                    </ul>
            </div>
        </nav>
        <!-- Sidenav (Hamburger Menu) -->
        <ul class="sidenav" id="mobile-menu">
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.profile')}}">My Profile</a></li>
            <li><a href="{{ url_for('auth.edit_profile')}}">Edit
                    Profile</a></li>
            <li>
                <div class="divider"></div>
            </li>
            <li><a href="{{ url_for('posts.new_post')}}">Create
                    New Post</a></li>
            <li><a href="{{ url_for('main.search_results', arg=current_user.username, filter='user') }}">View My
                    Posts</a></li>
            <li>
                <div class="divider"></div>
            </li>
            {% if current_user.is_active and current_user.is_authenticated and current_user.user_type == 'superuser' %}
            <li><a href="/admin"
                    class="waves-effect waves-light btn-small blue darken-2 white-text"
                    data-position="bottom" data-tooltip="Admin Page"><i class="fa-solid fa-user-gear"></i>Admin Page</a></li>
            {% endif %}
            <li><a href="#log_out" class="waves-effect waves-light btn-small modal-trigger"><i
                class="fa-solid fa-right-to-bracket"></i>Sign Out</a></li>
            {% else %}
            <li><a href="{{ url_for('main.home')}}">Home</a></li>
            <li><a href="{{ url_for('auth.signin')}}">Sign In</a></li>
            <li><a href="{{ url_for('auth.signup')}}" class="waves-effect waves-light btn">Sign
                    Up</a></li>
            {% endif %}
        </ul>
    </header>
    <main>
        <!-- Search Bar -->
        <div class="container">
            <div class="row search-field--container">
                <form class="col s12 m10 push-m1 l6 push-l3 scale-transition scale-out" id="search" method="POST"
                    action="{{ url_for('main.search_results')}}">
                    <fieldset class="row z-depth-5 valign-wrapper">
                        <legend class="visually-hidden">Search Bar</legend>
                        <div class="input-field col s2 xl1">
                            <button type="submit" class="btn yellow "><i class="material-icons">search</i><span
                                    class="visually-hidden">Open Search Bar</span></button>
                        </div>
                        <div class="input-field col s6 m8 l10">
                            <input type="text" name="search_field" id="autocomplete-input" class="autocomplete">
                            <label for="autocomplete-input">Looking for something?</label>
                        </div>
                        <div class="input-field col s3 m2">
                            <label for="filter_select" class="visually-hidden">Filter By</label>
                            <select id="filter_select" name="filter_select">
                                <option value="user" disabled selected>Filter By</option>
                                <option value="user">username</option>
                                <option value="lang">language</option>
                            </select>
                        </div>
                        <div class="input-field col s1">
                            <i class="material-icons center" data-target="search-field--container">close</i>
                        </div>
                    </fieldset>
                </form>
            </div>
            <!-- Flash Messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="visually-hidden">
                <span class="toast {{ category }}">{{ message }}</span>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% if title %}
            <h1 class="visually-hidden">{{ title }}</h1>
            {% else %}
            <h1 class="visually-hidden">Home Page</h1>
            {% endif %}
            {% block content%}
            {% endblock %}
        </div>
    </main>
    <!-- Footer -->
    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col s12 l6">
                    <h5 class="white-text brand-logo">DevBus</h5>
                    <p class="grey-text text-lighten-4">Ever wonder what would happen if StackOverflow and Twitter
                        merged? Well, wonder no more! This is the social media website for developer by developers.</p>
                </div>
                <div class="col s12 l4 offset-l2 social-media">
                    <h5 class="white-text">You can also find us:</h5>
                    <ul class="center">
                        <li class="col s4 m3 offset-m1 l4"><a class="grey-text text-lighten-3"
                                href="https://github.com/NyxHexen/CI_MS3_DevBus" target="_blank"><i
                                    class="fa-brands fa-github social-media-icon"></i><span class="visually-hidden">Open GitHub in
                                    a separate tab</span></a></li>
                        <li class="col s4 m3 offset-m1 l4"><a class="grey-text text-lighten-3" href="https://www.wikipedia.com"
                                target="_blank"><i class="fa-brands fa-wikipedia-w social-media-icon"></i><span
                                    class="visually-hidden">Open Wikipedia in a separate tab</span></a></li>
                        <li class="col s4 m3 offset-m1 l4"><a class="grey-text text-lighten-3" href="https://www.youtube.com"
                                target="_blank"><i class="fa-brands fa-youtube social-media-icon"></i><span
                                    class="visually-hidden">YouTube</span></a></li>
                        <li class="col s12 center"><i class="fa-solid fa-phone"></i><a class="grey-text text-lighten-3"
                                href="tel:+15551234" target="_blank"> +1-555-1234</a></li>
                        <li class="col s12 center"><i class="fa-solid fa-envelope"></i><a
                                class="grey-text text-lighten-3" href="mailto:admin@devbus.com" target="_blank">
                                admin@devbus.com</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2023 NyxHexen Copyright
            </div>
        </div>
    </footer>
    <!-- Modals -->
    <div id="log_out" class="modal">
        <div class="modal-content">
            <h4>Confirm Logout</h4>
            <p>Are you sure you want to sign out?</p>
        </div>
        <div class="modal-footer center">
            <a href="{{ url_for('auth.logout')}}" class="waves-effect waves-green btn-flat">Yes</a>
            <a class="modal-close waves-effect waves-green btn-flat">No</a>
        </div>
    </div>
    {% block modals %}
    {% endblock %}
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <!-- Compiled and minified Materialize JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Prism JS -->
    <script src="{{ url_for('static', filename='js/prism.js') }}"></script>
    <!-- Own JS -->
    <script src="{{ url_for('static', filename='js/main.min.js') }}"></script>
</body>

</html>

devbus/templates/sidenavs.html
<!-- User Sidenav -->
{% if current_user.is_authenticated %}
<div id="profile" class="row hide-on-small-and-down container">
    <div class="col m5 pull-m1 l4 pull-l2 xl3 pull-xl1">
        <div class="card z-depth-5">
            <div class="card-content">
                <!-- User Picture -->
                <div class="row">
                    <div class="col s8 push-s2">
                        <img class="circle responsive-img" src="{{ current_user.profile_image }}"
                            alt="User Profile Picture">
                    </div>
                </div>
                <!-- User Username & Bio -->
                <div class="row">
                    <div class="col profile-username s12 center-align">
                        {% if current_user.f_name %}
                        <span class="card-title">{{ current_user.f_name}}
                            {{ current_user.l_name }}</span>
                        <p class="center-align">@{{ current_user.username }}</p>
                        {% else %}
                        <span class="card-title">{{ current_user.username }}</span>
                        {% endif %}
                        <div class="divider"></div>
                        <!-- <p>{% if current_user.bio %} {{ current_user.bio }} {% else %} You {% endif %}</p> -->
                        <p>{% if current_user.bio %} {{ current_user.bio }} {% else %} You haven't added anything here yet... {% endif %}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<!-- Right-side Quick/Side Menu -->
<div id="quickmenu" class="row hide-on-med-and-down container">
    <div class="col l4 offset-l10 xl3 offset-xl10">
        {% if current_user.is_authenticated %}
        <div class="card card-content z-depth-5">
            <div class="collection">
                <a href="{{ url_for('posts.new_post')}}" class="collection-item deep-purple-text text-darken-3">Create New Post</a>
                <a href="{{ url_for('main.search_results', arg=current_user.username, filter='user') }}" class="collection-item deep-purple-text text-darken-3">View My Posts</a>
                <a href="{{ url_for('auth.edit_profile')}}" class="collection-item deep-purple-text text-darken-3">Edit Profile</a>
            </div>
        </div>
        {% else %}
        <div class="card">
            <div class="card-content center-align">
                <span class="card-title">New here?</span>
                <p>Sign up now to explore all that DevBus has to offer!</p>
                <br>
                <a href="{{ url_for('auth.signup') }}" class="waves-effect waves-light btn green">Sign Up</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>